const viewer=document.querySelector('.viewer'),large=viewer.querySelector('img'),prev=viewer.querySelector('.viewer-prev'),next=viewer.querySelector('.viewer-next'),caption=viewer.querySelector('.viewer-caption');
let origin,items=[],index=0,busy=false,hiddenImage;
const reduced=()=>matchMedia('(prefers-reduced-motion:reduce)').matches;
const rectQuad=(x,y,w,h)=>[[x,y],[x+w,y],[x+w,y+h],[x,y+h]];
function fitRect(img){const r=img.getBoundingClientRect(),s=getComputedStyle(img),left=parseFloat(s.paddingLeft),right=parseFloat(s.paddingRight),topPad=parseFloat(s.paddingTop),bottomPad=parseFloat(s.paddingBottom),w=r.width-left-right,h=r.height-topPad-bottomPad,ratio=img.naturalWidth/img.naturalHeight;const fitW=Math.min(w,h*ratio),fitH=fitW/ratio;return rectQuad(r.left+left+(w-fitW)/2,r.top+topPad+(h-fitH)/2,fitW,fitH);}
function sourceQuad(button){const img=button.querySelector('img');if(button.dataset.wallQuad){const space=button.closest('.room-space'),r=space.getBoundingClientRect(),scale=r.width/1280,q=JSON.parse(button.dataset.wallQuad),w=parseFloat(button.style.width),h=parseFloat(button.style.height),fit=Math.min(w/img.naturalWidth,h/img.naturalHeight),iw=img.naturalWidth*fit,ih=img.naturalHeight*fit,m=new DOMMatrix(homography(rectQuad(0,0,w,h),q));return rectQuad((w-iw)/2,(h-ih)/2,iw,ih).map(([x,y])=>{const p=m.transformPoint(new DOMPoint(x,y));return[r.left+p.x/p.w*scale,r.top+p.y/p.w*scale];});}return fitRect(img);}
function show(){const photo=items[index].querySelector('img');large.src=photo.src;large.alt=photo.alt;prev.disabled=index===0;next.disabled=index===items.length-1;caption.textContent=`${photo.alt} · ${index+1} / ${items.length}`;if(hiddenImage)hiddenImage.style.visibility='';hiddenImage=photo;hiddenImage.style.visibility='hidden';}
async function fly(from,to){if(reduced())return;const image=new Image();image.src=large.src;image.alt='';image.className='fly-image';image.style.width=large.naturalWidth+'px';image.style.height=large.naturalHeight+'px';viewer.append(image);large.style.visibility='hidden';try{await new Promise(resolve=>{const start=performance.now();function frame(now){const p=Math.min(1,(now-start)/650),ease=1-Math.pow(1-p,3),q=from.map((corner,i)=>corner.map((n,j)=>n+(to[i][j]-n)*ease));image.style.transform=homography(rectQuad(0,0,large.naturalWidth,large.naturalHeight),q);if(p<1)requestAnimationFrame(frame);else resolve();}frame(start);});}finally{image.remove();large.style.visibility='';}}
async function open(button){if(busy||viewer.open)return;busy=true;origin=button;items=[...button.closest('.portraits,.gallery,.black-room').querySelectorAll('.photo')];index=items.indexOf(button);const from=sourceQuad(button);show();try{await large.decode();viewer.showModal();await fly(from,fitRect(large));}finally{busy=false;}}
async function shut(){if(busy||!viewer.open)return;busy=true;try{await fly(fitRect(large),sourceQuad(items[index]));if(hiddenImage)hiddenImage.style.visibility='';hiddenImage=null;viewer.close();origin?.focus({preventScroll:true});}finally{busy=false;}}
function move(step){if(busy)return;const target=index+step;if(target<0||target>=items.length)return;index=target;show();}
document.querySelectorAll('.photo').forEach(button=>button.addEventListener('click',()=>open(button)));
prev.addEventListener('click',()=>move(-1));next.addEventListener('click',()=>move(1));viewer.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}if(e.key==='ArrowRight'){e.preventDefault();move(1);}});
let touch;viewer.addEventListener('touchstart',e=>{touch=e.touches.length===1?[e.touches[0].clientX,e.touches[0].clientY]:null;},{passive:true});viewer.addEventListener('touchend',e=>{if(!touch)return;const dx=e.changedTouches[0].clientX-touch[0],dy=e.changedTouches[0].clientY-touch[1];if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.3)move(dx<0?1:-1);touch=null;},{passive:true});
viewer.querySelector('.close').addEventListener('click',shut);viewer.addEventListener('cancel',e=>{e.preventDefault();shut();});viewer.addEventListener('click',event=>{if(event.target===viewer)shut();});
